from app.models.role import Role
from app.models.user import User
from app.models.page import Page
from app.models.site import Site
from app.models.site_alias import SiteAlias
from app.models.page_link import PageLink
from app.models.test_scenario import TestScenario
from app.models.test_suite import TestSuite
from app.models.setting import Setting
from app.models.test_case import TestCase
from app.models.test_execution import TestExecution
from app.models.page_link_test_case import PageLinkTestCase
from app.models.setting import Setting
