"""create page table

Revision ID: 33b5b767049e
Revises: 4f22aff4e95c
Create Date: 2025-12-09 08:19:20.956991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '33b5b767049e'
down_revision: Union[str, Sequence[str], None] = '4f22aff4e95c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('page_url', sa.String(length=512), nullable=False),
    sa.Column('status', sa.Enum('new', 'generating_metadata', 'generating_test_scenarios', 'generating_test_cases', 'test_cases_generated', 'generating_test_scripts', 'done', name='page_status'), nullable=False),
    sa.Column('page_title', sa.String(length=200), nullable=True),
    sa.Column('page_source', sa.Text(), nullable=True),
    sa.Column('page_metadata', mysql.JSON(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_page')),
    sa.UniqueConstraint('page_url', name=op.f('uq_page_page_url'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page')
    # ### end Alembic commands ###
