"""create test_scenario  table

Revision ID: 5135179b6540
Revises: ac025bc3c159
Create Date: 2025-12-09 08:20:35.265884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5135179b6540'
down_revision: Union[str, Sequence[str], None] = 'ac025bc3c159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_scenario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('data', mysql.JSON(), nullable=True),
    sa.Column('type', sa.Enum('auto-generated', 'manual', name='scenario_type'), nullable=False),
    sa.Column('category', sa.Enum('functional', 'auth-positive', 'auth-negative', 'ui-validation', 'validation', 'navigation', 'form', name='scenario_category'), nullable=True),
    sa.Column('script', sa.Text(), nullable=True),
    sa.Column('script_path', sa.String(length=255), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_scenario'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_scenario')
    # ### end Alembic commands ###
