"""create page_link  table

Revision ID: 7e9106303d28
Revises: 5135179b6540
Create Date: 2025-12-09 08:21:49.233417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e9106303d28'
down_revision: Union[str, Sequence[str], None] = '5135179b6540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_link',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('page_id_source', sa.Integer(), nullable=False),
    sa.Column('test_scenario_id_source', sa.Integer(), nullable=False),
    sa.Column('page_id_target', sa.Integer(), nullable=False),
    sa.Column('event_selector', sa.String(length=512), nullable=True),
    sa.Column('event_description', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_page_link'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page_link')
    # ### end Alembic commands ###
